name: Audit Workflow

on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint with KtLint
        run: ./gradlew audit
