name: CD/CI Workflow

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint with KtLint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy with Heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/simple-mailer-backend.git HEAD:master -f
